// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahmdzltfccwixzekrxvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFobWR6bHRmY2N3aXh6ZWtyeHZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwMjY4MDAsImV4cCI6MjA1NTYwMjgwMH0.qBlXoyYi6M7XCsiDLVNI4C4cBO4YPl92CiYqyCrhCkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);